#!/bin/bash
set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
SRC_DIR="${1:-$SCRIPT_DIR/chromium/src}"

if [ ! -d "$SRC_DIR" ]; then
    echo "Chromium source directory not found: $SRC_DIR" >&2
    exit 1
fi

cd "$SRC_DIR"

BRIDGE=chrome/browser/ui/android/extensions/java/src/org/chromium/chrome/browser/ui/extensions/ExtensionsMenuBridge.java
TOOLBAR=chrome/browser/ui/android/toolbar/java/src/org/chromium/chrome/browser/toolbar/extensions/ExtensionsToolbarCoordinatorImpl.java
CTA=chrome/android/java/src/org/chromium/chrome/browser/ChromeTabbedActivity.java
VERIFIER=chrome/browser/extensions/chrome_content_verifier_delegate.cc

for file in "$BRIDGE" "$TOOLBAR" "$CTA" "$VERIFIER"; do
    if [ ! -f "$file" ]; then
        echo "Expected file not found: $SRC_DIR/$file" >&2
        exit 1
    fi
done

# Repair a bad intermediate JNI annotation generated by an older patch.
sed -i 's|                ("std::string") String extensionId);|                @JniType("std::string") String extensionId);|' "$BRIDGE"

# Keep local zip/crx/unpacked extensions out of WebStore content verification.
sed -i 's|if (!InstallVerifier::IsFromStore(extension, context_)) {|if (!extension.from_webstore()) {|' "$VERIFIER"

# Startup stability: do not purge renderer caches automatically on every start.
sed -i '/clearVolatileRendererCaches();/d' "$CTA"

# Startup stability: extension toolbar button visibility must tolerate missing
# toolbar variants during first-launch layout inflation.
perl -0pi -e 'if (!/setHeliumMenuButtonVisibility/) { s|    private void showIphInternal\(\) \{|    private void setHeliumMenuButtonVisibility(boolean visible) {\n        if (mContainer == null) return;\n        View menuButton = mContainer.findViewById(R.id.extensions_menu_button);\n        if (menuButton == null) return;\n        menuButton.setVisibility(visible ? View.VISIBLE : View.GONE);\n    }\n\n    private void showIphInternal() {| }' "$TOOLBAR"

sed -i 's|if (mPrefService.getBoolean(Pref.PIN_EXTENSIONS_MENU_BUTTON)) { mContainer.findViewById(R.id.extensions_menu_button).setVisibility(View.VISIBLE); } else { mContainer.findViewById(R.id.extensions_menu_button).setVisibility(View.GONE); }|        setHeliumMenuButtonVisibility(mPrefService.getBoolean(Pref.PIN_EXTENSIONS_MENU_BUTTON));|' "$TOOLBAR"
sed -i 's|mContainer.findViewById(R.id.extensions_menu_button).setVisibility(isMenuButtonPinned() ? View.VISIBLE : View.GONE);|                setHeliumMenuButtonVisibility(isMenuButtonPinned());|' "$TOOLBAR"

perl -0pi -e 's|        mContainer\.findViewById\(R\.id\.extensions_menu_button\)\.setVisibility\(visibility\);|        View menuButton = mContainer.findViewById(R.id.extensions_menu_button);\n        if (menuButton != null) {\n            menuButton.setVisibility(visibility);\n        }|' "$TOOLBAR"

echo "Applied hotfixes to $SRC_DIR"
